### ISSUE TITLE
Não é possível apagar collections inseridas previamente (>32chars) [BUG]

### ISSUE THREAD

**Issue by josaum** [jquant/jai-sdk#150]
**Describe the bug**
Não é possível apagar collections antigas, cujo nome supera 32 caracteres.

**To Reproduce**
Tente apagar uma collection que possui um nome com mais de 32 caracteres.

**Expected behavior**
Ela deveria ser apagada.

**Screenshots**
![image](https://user-images.githubusercontent.com/8642345/112646233-0a70d400-8e26-11eb-8c11-d0a02375e4c7.png)

**Comment by josaum** [comment]
exemplo: "h_produtos_01eba082d9438f42701e1bb_unsup"

**Comment by ricardokazu** [comment]
will be solved on next version :)
