### ISSUE TITLE
j.setup está retornando internal server error [BUG]

### ISSUE THREAD

**Issue by josaum** [jquant/jai-sdk#151]
**Describe the bug**
Não consigo rodar nenhuma função do JAI que possua SETUP.

**To Reproduce**
tentar fazer qualquer setup usando a chave da subscription: "dionisio contatinho unlimited"

**Expected behavior**
deveria executar a função pedida, ao invés de retornar internal server error.

**Additional context**
Desconfio que seja um problema de LOG travado com essa subscription específicamente, porque quando tentei com outra chave deu certo.

**Comment by p-freire** [comment]
Successfully ran a self-supervised setup using Titanic dataset on this particular subscription. Please check if you can run a setup on your machine as well. I'll close this issue, but please reopen it if the problem persists.
