### ISSUE TITLE
Sanity não aceita overwrite=True [BUG]

### ISSUE THREAD

**Issue by laurademenezes** [jquant/jai-sdk#160]
**Describe the bug**
Sanity não está aceitando o parâmetro overwrite = True e está entrando direto no predict

**To Reproduce**
1. rode um sanity
2. rode novamente com overwrite=True

**Expected behavior**
Treinar novamente

**Screenshots**
![image](https://user-images.githubusercontent.com/60359026/112905389-af0e4280-90c0-11eb-87d5-4b2df98043fe.png)

**Comment by p-freire** [comment]
Fixed with PR #162
