### ISSUE TITLE
TextEdit RuntimeError [BUG]

### ISSUE THREAD

**Issue by laurademenezes** [jquant/jai-sdk#173]
**Describe the bug**
Quando tento preprocessar uma series com o TextEdit ele retorna um RuntimeError. Os demais db_types rodaram normalmente nessa mesma series

**Screenshots**
![image](https://user-images.githubusercontent.com/60359026/113300013-df79fa80-92d3-11eb-9753-a80d050b92af.png)

**Comment by ricardokazu** [comment]
We updated the API, everything should be working now.
