### ISSUE TITLE
Overwrite ainda está dando internal server error[BUG]

### ISSUE THREAD

**Issue by laurademenezes** [jquant/jai-sdk#181]
**Describe the bug**
Overwrite retorna que a collection a ser sobrescrita ainda não existe (mas existe) e quando tenta inserir novos dados retorna internal server error

**Expected behavior**
Sobrescrever a collection

**Screenshots**
![image](https://user-images.githubusercontent.com/60359026/113941733-09e91d80-97d6-11eb-9e07-9f4384a9cf54.png)

![image](https://user-images.githubusercontent.com/60359026/113941908-60eef280-97d6-11eb-852b-15ec58d63450.png)
![image](https://user-images.githubusercontent.com/60359026/113941964-76641c80-97d6-11eb-8ec6-4de3b2ab138a.png)

**Comment by laurademenezes** [comment]
Usando uma base treinada hoje e setando o overwrite =True funcionou. Não sei se o erro que é aleatório ou se a data da criação da collection interfere em alguma coisa

**Comment by p-freire** [comment]
Ran different applications and setups using `overwrite=True` and could not reproduce internal server error. Closing issue, but if you get a persistent error behavior overwriting, please reopen it.
