### ISSUE TITLE
Adicionar exception ou ignorar quantile [... ,0., ...] no modo quantile_regression [BUG]

### ISSUE THREAD

**Issue by josaum** [jquant/jai-sdk#209]
**Describe the bug**
Se o usuário envia para a JAI um quantile 0. dentro da lista de quantiles de uma task to tipo "quantile_regression", não há exception nenhuma, mas os resultados vêm completamente alterados.

**To Reproduce**
Criar um j.setup com db_type = Supervised e task=quantile_regression. Introduzir um quantile 0 na lista de quantiles

exemplo: 'quantiles': [0. , 0.5, 0.99]

**Expected behavior**
Ou o quantile 0 deveria ser ignorado ou então uma exception deveria ser levantada, impedindo o treinamento do modelo.

**Comment by ricardokazu** [comment]
Fixed, now quantiles will always be simetric
