### ISSUE TITLE
crash quando a coluna do dataframe possui mais tipos misturados [BUG]

### ISSUE THREAD

**Issue by josaum** [jquant/jai-sdk#210]
**Describe the bug**
Uma coluna do dataframe com tipos diferentes (ex: int e str) faz com que a JAI dê exception.

**To Reproduce**
Envie um dataframe à JAI (j.setup) com uma coluna contendo mixed types

**Expected behavior**
JAI deveria sempre dar cast para objeto/string e não dar exception --> e avisar ao usuário que fez isso, assim como o pandas faz quando importa dados com mixed types.

**Screenshots**
Em geral esse é o erro:

![image](https://user-images.githubusercontent.com/8642345/116896316-82db6980-ac0a-11eb-87a3-fafef49c0589.png)

**Comment by ricardokazu** [comment]
fixed :)
