### ISSUE TITLE
overwrite=True não funciona se o dbtype mudar

### ISSUE THREAD

**Issue by josaum** [jquant/jai-sdk#49]
a msg de erro leva o usuario a acreditar que ele pode reutilizar o mesmo db_name se colocar a flag overwrite=True.

no entanto isso não é verdade caso o type do db mudar, de Supervised para EditText por exemplo.

**Comment by ricardokazu** [comment]
Acho que esse bug já foi resolvido. Se ele ainda persistir, abrir essa issue de novo :)
