### ISSUE TITLE
Unsupervised - decoder_layer:2L exception

### ISSUE THREAD

**Issue by josaum** [jquant/jai-sdk#80]
Erro ao tentar utilizar o seguinte setup:

`j.setup(name_unsupervised, data, db_type='Unsupervised', mycelia_bases=[{'db_parent': name, 'id_name':'id_comentarios'}], hyperparams={'encoder_layer':'2L', 'decoder_layer':'2L'})`

**Not Implemented Exception**

**Comment by josaum** [comment]
![image](https://user-images.githubusercontent.com/8642345/109223409-4cf8af80-7799-11eb-8f8e-b7bfe0c089f6.png)

**Comment by ricardokazu** [comment]
é erro na api e erro na documentação, o certo é "2Linears"

**Comment by josaum** [comment]
mas no encoder é 2L

**Comment by ricardokazu** [comment]
fix na API
