### ISSUE TITLE
applications.resolution - filtrar id==query id ?

### ISSUE THREAD

**Issue by josaum** [jquant/jai-sdk#81]
dúvida: deveríamos retornar os casos onde Query ID == ID ? Porque estes são trivialmente iguais e sempre têm que ser filtrados posteriormente.

**Comment by josaum** [comment]
![image](https://user-images.githubusercontent.com/8642345/109515825-49f60b80-7a86-11eb-99bb-2f390c3c2819.png)

**Comment by josaum** [comment]
![image](https://user-images.githubusercontent.com/8642345/109515995-76aa2300-7a86-11eb-9ed3-708960ebec05.png)

**Comment by ricardokazu** [comment]
processamos esses casos utilizando as funções no jai.process, temos os parametros return_self para filtrar esses casos
