### ISSUE TITLE
acredito que o sample do Sanity deveria ser stratified

### ISSUE THREAD

**Issue by josaum** [jquant/jai-sdk#82]
nesse trecho de código aqui:
https://github.com/jquant/jai-sdk/blob/473895cd5a0de5f5165d885d0233dab3ed04cc32/jai/applications.py#L300-L307

Acredito que deveríamos implementar uma espécie de stratified sample para gerar as labels de consistente e inconsistente.

**Comment by ricardokazu** [comment]
descreva o que seria isso
